suppressMessages(library(httr))
suppressMessages(library(tidyr))
suppressMessages(library(dplyr))
suppressMessages(library(stringr))
suppressMessages(library(highcharter))
suppressMessages(library(dime))
suppressMessages(library(xml2))
suppressMessages(library(rvest))
suppressMessages(library(purrr))
suppressMessages(library(crayon))
source("../R/wikipedia/ingestion.R")

cat(magenta("###### Reading Oscars Data and Filtering on Persons ######\n"))
allMovies = read.csv("../data/oscars.csv", stringsAsFactors = FALSE)
persons = filter(allMovies, Awardee == "Person")

cat(magenta("###### Fetching Wikipedia IDs ######\n"))
uniquePeople = distinct(persons, person)
wikipeidaIds = as.list(uniquePeople)$person %>% map(fetchWikipediaIDs)
uniquePeople$id = as.character(wikipeidaIds)
cat(magenta("###### Fetching NNDB IDs ######\n"))
nnddId = as.list(uniquePeople)$id %>% map(fetchArticleEntities)
uniquePeople$nnddId = as.character(nnddId)

cat(magenta("###### Fetching Profile Data from NNDB ######\n"))
performers = fetchAllPersonMetaData(uniquePeople)
cat(magenta("###### Joining everything together and cleaning up... ######\n"))
allPerformers = left_join(uniquePeople, performers, by = "nnddId")
allPerformers$person = str_replace_all(allPerformers$person, "\\s$", "")
allPerformers = distinct(allPerformers)
cat(magenta("###### Writing File... ######\n"))
write.csv(allPerformers, "../data/performers.csv")
cat(green("#############################\n"))
cat(green("###### Done! ######\n"))
cat(green("#############################\n"))